version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: ${DK_PG_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "${PG_PORT}:${PG_PORT}"
      
volumes:
    nodemodules: {}